#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

apt-get install -y ceph \
        haveged \
        openssh-client \
        dnsutils \
        radosgw \
        lighttpd \
        --no-install-recommends

cat > /var/www/s3gw.fcgi <<EOF
#!/bin/sh
/usr/bin/radosgw -c /etc/ceph/ceph.conf
EOF
chmod +x /var/www/s3gw.fcgi
